import Hero from '@/components/Hero';
import FeatureStrip from '@/components/FeatureStrip';
import SectionTitle from '@/components/SectionTitle';
import CarrierInquiryForm from '@/components/CarrierInquiryForm';
import AudienceGrid from '@/components/AudienceGrid';
import StatsBand from '@/components/StatsBand';
import FAQ from '@/components/FAQ';
import Icon from '@/components/Icon';

export const metadata = { title:'Carrier Inquiry', description:'Submit a carrier inquiry to Siranay Freight Management for dispatch and carrier support services.', alternates:{canonical:'/carrier-inquiry'} };

export default function CarrierInquiryPage(){return <>
  <Hero compact className="hero-carrier-inquiry" eyebrow="CARRIER INQUIRY" title="Let's Get You {accent}" accent="Moving." text="Tell us about your operation and how Siranay Freight Management can support your goals. We'll review your information and follow up promptly to discuss next steps." image="/images/hero-inquiry-truck.webp" primary="Start Inquiry" primaryHref="#inquiry" secondary="Contact Us" secondaryHref="/contact" />
  <FeatureStrip />
  <section className="section inquiry-section" id="inquiry"><div className="container inquiry-layout"><div className="inquiry-main"><SectionTitle title="Carrier Inquiry {accent}" accent="Form" text="Please complete the form below and we'll be in touch soon." align="left"/><CarrierInquiryForm/></div><aside className="inquiry-side"><div className="accepting-banner"><img src="/images/january-banner.webp" alt="Now accepting new carrier clients"/><div className="banner-overlay"><h3>Now Accepting<br/>New Carrier Clients<br/><span>for January 2027</span></h3><p>We are currently onboarding a limited number of carrier clients for January 2027. Submit your inquiry now to get on our list and secure your spot.</p></div></div><div className="next-box"><h2>What Happens Next?</h2>{[['1','We Review Your Inquiry','We review your information and learn about your goals, lanes, and equipment.'],['2','Initial Conversation',"We will reach out to discuss your needs and answer any questions."],['3','Setup & Onboarding','Once approved, we get you set up, align on preferences, and prepare for dispatch.'],['4',"Let's Keep You Moving",'We handle communication, coordination, and support so you can focus on driving.']].map(([n,t,d])=><div className="next-step" key={n}><span>{n}</span><div><strong>{t}</strong><p>{d}</p></div></div>)}</div><div className="ready-box"><Icon name="document" size={34}/><div><h3>What to Have Ready</h3><p>Helpful information includes:</p><ul><li>Operating authority details (USDOT / MC)</li><li>Preferred lanes and regions</li><li>Equipment information</li><li>Service goals and availability</li><li>Best contact information</li></ul></div></div></aside></div></section>
  <section className="section section-muted"><div className="container"><SectionTitle title="Why Start With Siranay?" align="left" text="We're more than a dispatch service — we're a long-term partner for owner-operators and small fleets."/><div className="value-grid six">{[['users','Personalized Service','We take time to understand your operation and match you with the right opportunities.'],['chat','Bilingual English/French Communication','Direct support in English or French, with a bilingual team that understands your needs.'],['pin','Cross-Border Knowledge','Deep experience with U.S. & Canada lanes, border requirements, and compliance.'],['truck','Support for Small Fleets','Built for owner-operators and small fleets with flexible solutions and dedicated support.'],['route','Professional Dispatch Guidance','We handle broker communication, negotiate on your behalf, and keep you informed.'],['chart','Long-Term Partnership','We focus on building lasting relationships and helping you grow your business.']].map(([i,t,d])=><div className="value-card" key={t}><span className="emoji-icon"><Icon name={i} size={39}/></span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
  <section className="section"><div className="container"><SectionTitle title="Who This Inquiry Is For" align="left"/><AudienceGrid links={false}/></div></section>
  <section className="section section-muted"><div className="container"><SectionTitle title="What We Help You With" align="left" text="From finding the right loads to handling the details, we provide end-to-end support so you can focus on driving."/><div className="help-grid">{[['pin','Load Planning & Dispatch','We find and plan loads that match your equipment, lanes, and goals.'],['chat','Broker Communication','We handle communication, negotiate rates, and keep you informed every step of the way.'],['document','Paperwork & Setup','We help with carrier setup, documentation, and compliance guidance.'],['dollar','Billing / Invoicing Support','We assist with invoicing, follow-ups, and payment tracking to keep your business moving.']].map(([i,t,d])=><div className="help-card" key={t}><Icon name={i} size={34}/><div><h3>{t}</h3><p>{d}</p></div></div>)}</div></div></section>
  <section className="section"><div className="container"><SectionTitle title="Our Onboarding Process" align="left" text="A simple, straightforward process to get you on the road with Siranay."/><div className="onboarding-line">{[['01','Inquiry Submission','Complete the form with your carrier details.'],['02','Qualification Review','We review your information and verify details.'],['03','Discovery Call',"We will discuss your goals, lane preferences, and needs."],['04','Setup & Alignment',"Once approved, we will get you set up and align on next steps."],['05','Ongoing Dispatch Support','We keep you moving with dedicated support and communication.']].map(([n,t,d])=><div key={n}><span>{n}</span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
  <StatsBand title="By the Numbers"/>
  <section className="section"><div className="container"><SectionTitle title="Frequently Asked Questions" align="left"/><FAQ items={[["Who should fill out the carrier inquiry form?","Owner-operators, small fleets, new carriers, and cross-border trucking businesses looking for dispatch or carrier support can submit the form."],["Do you work with new carriers?","Yes. We can support newly established carriers with setup, dispatch processes, and communication."],["Do you support U.S. – Canada cross-border operations?","Yes. Cross-border U.S.–Canada support and bilingual English/French communication are core service areas."],["Can I request French-language communication?","Yes. You can select French as your preferred communication language in the form."],["How soon will someone contact me?","Response time depends on inquiry volume, but we aim to review new inquiries promptly and follow up as soon as possible."]]}/></div></section>
</>}
