import Image from 'next/image';
import Icon from '@/components/Icon';
import './about-reference.css';
export const metadata = { title:'About', description:'Meet Simone Harris and the team behind Siranay Freight Management.', alternates:{canonical:'/about'} };
const values=[['users','Team Support','You get a team, not just one dispatcher.'],['chat','Bilingual Communication','English and French speaking team members.'],['handshake','Reliable Service','Organized support and clear communication.'],['shield','Continuity','Your operation stays supported, even when one team member is unavailable.']];
export default function AboutPage(){return <main className="about-reference">
<section className="about-ref-hero"><div className="about-ref-wide"><span className="about-ref-eyebrow">ABOUT SIRANAY</span><h1>Built on Experience.<br/><em>Built for Carriers.</em></h1><p>Siranay Freight Management LLC provides professional dispatch and carrier support for owner-operators and small fleets throughout the United States, with specialized bilingual English/French support for carriers operating U.S.–Canada cross-border lanes.</p><p>Our approach is simple: reliable communication, organized dispatch support, and a team that understands the importance of keeping your operation moving.</p></div></section>
<section className="about-ref-founder"><div className="about-ref-wide about-ref-founder-grid"><div className="about-ref-photo"><Image src="/images/simone-harris.webp" alt="Simone Harris, Siranay Freight Management co-founder" fill sizes="(max-width:700px) 90vw, 30vw" priority/></div><div><span className="about-ref-eyebrow">MEET THE FOUNDER</span><h2>Simone Harris</h2><span className="about-ref-role">CO-FOUNDER, SIRANAY FREIGHT MANAGEMENT LLC</span><p>Siranay Freight Management was founded by Simone Harris, an experienced entrepreneur and operations professional with a background in dispatch coordination, customer service, and transportation support.</p><p>Simone spent approximately 15 years with Verizon, including six years in dispatch operations coordinating field technicians across assigned service areas. Her work required careful scheduling, constant communication, problem-solving, and keeping technicians on track to meet customer commitments.</p><p>Earlier in her career, Simone also worked in truck dispatch operations at the Port of Wilmington, Delaware, coordinating auto-transport trucks carrying newly manufactured vehicles from the port. That experience provided firsthand exposure to driver coordination, scheduling, communication, and the importance of keeping transportation operations moving efficiently.</p><p>As a longtime entrepreneur, Simone understands that running a business means watching costs, protecting customer relationships, making good decisions, and keeping revenue moving. That combination of dispatch experience, operations management, transportation exposure, and entrepreneurship is the foundation of Siranay.</p><blockquote><span aria-hidden="true">“</span><div>“Good dispatch is more than finding a load.<br/>It’s communication, organization, planning ahead,<br/>and keeping people moving.”<cite>— Simone Harris, Co-Founder</cite></div></blockquote></div></div></section>
<section className="about-ref-team"><div className="about-ref-wide about-ref-team-grid"><div><span className="about-ref-eyebrow">BUILT AS A TEAM</span><h2>More Than One Dispatcher</h2><p>Siranay was built around the idea that professional dispatch support shouldn’t depend on just one person.</p><p>Our team brings together professionals with strengths in dispatch operations, organization, customer service, communication, and problem-solving.<br/>With English- and French-speaking team members, we’re positioned to support carriers operating throughout the United States as well as those running U.S.–Canada cross-border lanes.</p><p>Our team-based approach provides greater continuity for the carriers we serve, with information and dispatch activity organized so that support doesn’t rest only on one individual.</p><p><strong>A team that knows your operation — not just a dispatcher who knows your name.</strong></p></div><div className="about-ref-values">{values.map(([icon,title,text])=><article key={title}><span><Icon name={icon} size={32}/></span><h3>{title}</h3><p>{text}</p></article>)}</div></div></section></main>}
