import Image from 'next/image';
import Link from 'next/link';
import Hero from '@/components/Hero';
import SectionTitle from '@/components/SectionTitle';
import AudienceGrid from '@/components/AudienceGrid';
import StatsBand from '@/components/StatsBand';
import FAQ from '@/components/FAQ';
import Icon from '@/components/Icon';

export const metadata = { title:'About', description:'Meet founder Simone Harris and learn about Siranay Freight Management, its values, experience, and carrier-first approach.', alternates:{canonical:'/about'} };

export default function AboutPage(){return <>
  <Hero compact className="hero-about" eyebrow="ABOUT SIRANAY" title="{accent} Communication. Operations." accent="People." text="A commitment to people, reliable communication, and keeping freight moving." image="/images/hero-about-truck.webp" primary="Our Story" primaryHref="#story" secondary="Contact Us" secondaryHref="/contact" />

  <section className="section founder-section" id="story"><div className="container founder-grid">
    <div className="founder-photo"><Image src="/images/founder-simone.webp" alt="Simone Harris, Founder and Executive Director of Operations" fill sizes="(max-width:800px) 100vw, 30vw" priority/></div>
    <div className="founder-copy"><span className="eyebrow">MEET THE FOUNDER</span><h1 className="founder-name">Simone Harris</h1><strong className="founder-role">FOUNDER & OWNER</strong>
      <p>Siranay Freight Management was founded by Simone Harris, an experienced operations and dispatch professional with more than 15 years of experience in the transportation industry.</p>
      <p>Before launching Siranay, Simone spent years managing service demands, coordinating teams, solving problems, and keeping operations running efficiently. She created Siranay to combine that experience with a focus on helping owner-operators and small carriers spend less time on the administrative side of the road and more time moving freight.</p>
      <p>Simone is passionate about people, clear communication, and helping small businesses grow and succeed.</p>
    </div>
    <aside className="founder-side"><div className="story-card"><span className="eyebrow">OUR STORY</span><h2>Why Siranay?</h2><p><strong>Our name is personal.</strong></p><p>Siranay was created from the names of the founder and her children — a reminder that this company was built around family, opportunity, and creating something designed to last.</p><div className="story-heart">♡ <span>Family inspires the work we do and the way we support the carriers we serve.</span></div></div><div className="road-card"><Image src="/images/about-road.webp" alt="Open highway at sunset" fill sizes="300px"/><span>More Miles.<br/>Less Hassle.</span></div><div className="mission"><Icon name="route" size={34}/><div><span className="eyebrow">OUR MISSION</span><p>To provide reliable dispatch and carrier support with clear communication, professional service, and a focus on helping owner-operators and small fleets succeed.</p></div></div></aside>
  </div></section>

  <section className="section section-muted"><div className="container"><SectionTitle eyebrow="OUR VALUES" title="What Drives Us" text="Our values guide everything we do. They shape how we work, how we communicate, and how we support the carriers and partners we serve." align="left"/><div className="value-grid five">{[['users','PEOPLE FIRST','We build strong relationships and provide personalized support.'],['chat','CLEAR COMMUNICATION','Responsive, honest, and proactive communication.'],['shield','SOLUTIONS FOCUSED','We solve problems and keep you moving forward.'],['check','RELIABILITY','You can count on us to follow through and be there when it matters.'],['star','YOUR SUCCESS MATTERS','When you succeed, we succeed. Your goals are always a priority.']].map(([i,t,d])=><div className="value-card" key={t}><span className="soft-icon"><Icon name={i} size={35}/></span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>

  <section className="journey"><div className="container"><div className="journey-head"><div><span className="eyebrow light">OUR JOURNEY</span><h2>Built on Experience</h2></div><p>Siranay Freight Management was built from years of hands-on experience in operations, dispatch, and carrier support. Here's a look at the journey that led to where we are today.</p></div><div className="timeline">{[['2009 – 2015','Operations Experience','Gained valuable experience in transportation operations, customer service, and logistics management.'],['2016 – 2020','Dispatch Leadership','Managed service demands, coordinated teams, and developed a deep understanding of carrier needs and industry challenges.'],['2021','Bilingual & Cross-Border Specialization','Expanded expertise in U.S. & Canada operations, with a focus on bilingual support and cross-border logistics.'],['2024','Siranay Freight Management Founded','Launched Siranay to help owner-operators and small carriers get the support they need to grow and succeed.']].map(([y,t,d])=><div className="timeline-item" key={y}><span className="timeline-dot"></span><strong>{y}</strong><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>

  <section className="section"><div className="container"><SectionTitle title="Why Carriers Choose Siranay" align="left" text="We understand what carriers need built from experience, communication, and reliable support."/><div className="value-grid six">{[['chat','Bilingual Support','English and French communication to better serve you.'],['pin','U.S. & Canada Cross-Border Knowledge','Experience in cross-border operations, regulations, and lane opportunities.'],['headset','Responsive Communication','We are always accessible and keep you informed every step of the way.'],['users','Personalized Carrier Support','Tailored service to fit your goals, lanes, and equipment.'],['truck','Small Fleet Friendly','We specialize in owner-operators and small fleets.'],['handshake','Honest & Transparent Service','No hidden fees, no false promises — just reliable support you can trust.']].map(([i,t,d])=><div className="value-card" key={t}><span className="soft-icon"><Icon name={i} size={32}/></span><h3>{t}</h3><p>{d}</p></div>)}</div></div></section>
  <StatsBand title="Proven Experience. Real Results."/>
  <section className="section"><div className="container"><SectionTitle title="Who We Support" align="left"/><AudienceGrid/></div></section>
  <section className="section approach-section"><div className="container approach-grid"><div className="approach-image"><Image src="/images/partner-road.webp" alt="Truck driver and highway" fill sizes="(max-width:900px) 100vw, 40vw"/></div><div><span className="eyebrow">OUR APPROACH</span><h2>A Partner on the Road. <span>Not Just a Service.</span></h2><p>We believe in building real relationships with the carriers we work with. Our goal is to be more than a dispatch service — we're a partner you can count on, providing proactive support, clear communication, and professional service so you can focus on what you do best: driving.</p><Link href="/carrier-inquiry" className="btn btn-gold">Work With Siranay →</Link></div><div className="approach-list">{['Dedicated Support','Fewer Delays','Better Broker Communication','Professional Service'].map((x,i)=><p key={x}><span>{i+1}</span><strong>{x}</strong></p>)}</div></div></section>
  <section className="section"><div className="container"><SectionTitle title="Frequently Asked Questions" align="left"/><FAQ items={[["What makes Siranay different?","Siranay combines operational experience, carrier-focused dispatch support, bilingual English/French communication, and a practical approach built around owner-operators and small fleets."],["Do you support U.S. & Canada operations?","Yes. Cross-border U.S.–Canada support is a core part of our service focus."],["Do you work with small fleets?","Yes. Our support model is specifically designed for owner-operators and small fleets."],["How do you communicate with drivers?","We use clear, responsive communication through agreed channels and can support English or French communication."],["How do I get started?","Start with the carrier inquiry form. We'll review your information and follow up to discuss your operation and next steps."]]}/></div></section>
</>}
